INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Citi Double Cash Back", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Discover It Credit Card", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Capital One Savor", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "AMEX Blue Cash", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "BofA Cash Card", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Amazon Store Card", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Chase Sapphire", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "TD Cash Card", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Apple Card", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Capital One Quicksilver", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "TJX Rewards Card", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Costco Citi Card", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Costco Citi - Syd", "Credit Card", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Venmo", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "SquareCash", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - Citi", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - Discover", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - Savor", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - AMEX", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - TD", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - Amazon Card", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - B of A", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Cashback - Citi Costco", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Paypal", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Vangaurd", "Investment", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "TD Bank", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Treasury Direct", "Investment", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Tower FCU Checking", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Tower FCU Savings", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Capital One Checking", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Capital One Savings", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "HSA", "Bank", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "401k", "Investment", "Actual", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "401k - Syd", "Investment", "Actual", 0.0);
