INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Clothing", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Gifts", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Home", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Pupper", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Grooming", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Nail Salon", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Furniture", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Apartment Stuff", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Business", "Personal", "Paper", 0.0);
INSERT INTO myServer.account(id, name, parent_category, type, balance) VALUES (UUID(), "Donations", "Personal", "Paper", 0.0);
