version: "3.7"

services:
  mysql:
    image: mysql
    ports:
      - 6605:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql



