openapi: 3.0.0
info:
  title: Finances Account API
  version: "1.0.1"
  description: API endpoints for Account CRUD operations in the Finances app.
paths:
  /accounts:
    get:
      summary: Retrieve all accounts
      operationId: getAccounts
      responses:
        '200':
          description: A list of accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    post:
      summary: Create a new account
      operationId: createAccount
      requestBody:
        description: Account object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: Account created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /accounts/id/{id}:
    get:
      summary: Retrieve a specific account by ID
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          description: Numeric ID of the account to retrieve.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Account retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found.
    put:
      summary: Update an existing account
      operationId: updateAccount
      parameters:
        - name: id
          in: path
          description: Numeric ID of the account to update.
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated account object.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found.
    delete:
      summary: Delete an account
      operationId: deleteAccount
      parameters:
        - name: id
          in: path
          description: Numeric ID of the account to delete.
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Account deleted successfully.
  /accounts/name/{name}:
    get:
      tags:
        - "Accounts"
      summary: "Get account by name"
      operationId: "getAccountByName"
      parameters:
        - name: "name"
          in: "path"
          description: "The name that needs to be fetched."
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: "Account not found"
components:
  schemas:
    Account:
      type: "object"
      x-jpa: true
      properties:
        id:
          type: "string"
          x-idField: true
          x-generatedId: true
        name:
          type: "string"
        type:
          type: "string"
          x-typeEnum: true
        balance:
          type: "number"
          format: "float"
        parentCategory:
            type: "string"
