/**
 * Cheabs Finances
 * Service to finances
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ParentCategory } from "./parentCategory";


export interface Account { 
    id?: string;
    name?: string;
    type?: string;
    balance?: number;
    amount?: number;
    parentCategory?: ParentCategory;
    rollover?: number;
}

