/**
 * Cheabs Finances
 * Service to finances
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import * as BigNumber from 'bignumber.js';


export interface Transaction { 
    id?: string;
    description?: string;
    creditAccount?: Account;
    debitAccount?: Account;
    amount?: BigNumber.BigNumber;
    date?: string;
}

